In [60]:
import pandas as pd
import numpy as py
from sklearn import linear_model
from word2number import w2n

In [61]:
file_path = r'C:\Users\LENOVO\All Data Science\All CSV\hiring.csv'
df = pd.read_csv(file_path)
df

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [62]:
print(df['experience'].dtype)

object


In [63]:
df['experience'] = df['experience'].astype(str)

In [64]:
df['experience'] = df['experience'].apply(w2n.word_to_num)

In [65]:
df.experience

0     0
1     0
2     5
3     2
4     7
5     3
6    10
7    11
Name: experience, dtype: int64

In [67]:
df.test_score

0     8.0
1     8.0
2     6.0
3    10.0
4     9.0
5     7.0
6     NaN
7     7.0
Name: test_score, dtype: float64

In [68]:
df.test_score=df.test_score.fillna(df.test_score.median())

In [69]:
df.test_score


0     8.0
1     8.0
2     6.0
3    10.0
4     9.0
5     7.0
6     8.0
7     7.0
Name: test_score, dtype: float64

reg=linear_model.LinearRegression()
reg.fit(df[['experience','test_score','interview_score']], df.salary)


In [71]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

TypeError: only size-1 arrays can be converted to Python scalars

In [75]:
reg.intercept_

17737.26346433771

In [76]:
reg.predict([[2,9,6]])

C:\Users\LENOVO\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

In [77]:
reg.predict([[12,10,10]])

C:\Users\LENOVO\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])